config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{ 
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root  'home#index'

  resources :home, only:[:index] do
    collection do
      get 'chat', 'other', 'seek'
    end
  end
  resources :tweets do
    member do
      get 'discussion'
    end
    collection do
      get 'search'
    end
    resources :tweet_comments, only: [:create]
  end

  resources :users,  only:[:index, :show] do
    collection do
      get 'follow'
    end
  end
  resources :reactions, only:[:create]
  resources :matching, only:[:index]
  resources :chat, only:[:create] 
  resources :chat_message, only:[:show, :create]
  resources :notifications, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_message.rb
class ChatMessage < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user

  validates :message, presence: true, length: { maximum: 500 }

  # after_create_commit { MessageBroadcastJob.perform_later self }

end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :chat_room_users
  has_many :chat_messages
end

app/models/chat_room_user.rb
class ChatRoomUser < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user
end

app/models/notification.rb
class Notification < ApplicationRecord

  default_scope -> { order(created_at: :desc) }
  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :to_user, class_name:"User"
  belongs_to :from_user, class_name:"User"

  enum status:{ like:0, dislike:1 }

  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = Notification.new(
        visitor_id: from_user_id,
        visited_id: to_user_id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  validates :to_user_id, presence: true
  validates :from_user_id, presence: true
  validates :status, presence: true
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belogns_to :user
end

app/models/team.rb
class Team < ActiveHash::Base
  self.data = [
    { id: 1, name: '秋田ノーザンハピネッツ', image: 'image/about01_02.png' },
    { id: 2, name: '横浜ビー・コルセアーズ', image: 'image/fl_club_primary.png' },
    { id: 3, name: '新潟アルビレックスBB',image: 'image/img_flag.gif' },
    { id: 4, name: '富山グラウジーズ',image: 'image/富山.png' },
    { id: 5, name: 'レバンガ北海道',image: 'image/square_levanga_logo.png' },
    { id: 6, name: '宇都宮ブレックス',image: 'image/ph00162920.png' },
    { id: 7, name: '千葉ジェッツ',image: 'image/chibajets_logo_2018-01.png' },
    { id: 8, name: 'アルバルク東京',image: 'image/alvark.png' },
    { id: 9, name: 'サンロッカーズ渋谷',image: 'image/sr.png' },
    { id: 10, name: '川崎ブレイブサンダース',image: 'image/201807022050_2-600x0.png' },
    { id: 11, name: '三遠ネオフェニックス',image: 'image/_____________.png' },
    { id: 12, name: '滋賀レイクスターズ',image: 'image/logo.png' },
    { id: 13, name: '京都ハンナリーズ',image: 'image/京都.jpg' },
    { id: 14, name: '大阪エヴェッサ',image: 'image/8FEcLku_.png' },
    { id: 15, name: '琉球ゴールデンキングス',image: 'image/rg.png' },
    { id: 16, name: '信州ブレイブウォリアーズ',image: 'image/FPfXFwON_400x400.png' },
    { id: 17, name: '島根スサノオマジック',image: 'image/島根.jpeg' },
    { id: 18, name: '広島ドラゴンフライズ',image: 'image/広島.png' },
    { id: 19, name: 'シーホース三河',image: 'image/三河.png' },
    { id: 20, name: '名古屋ダイヤモンドドルフィンズ',image: 'image/team-logo01.png' },
    { id: 21, name: 'その他', image: 'image/その他.png' }
  ]
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :team
  belongs_to :user
  has_many :tweet_comments, dependent: :destroy
  mount_uploader :image, ImageUploader

  with_options presence: true do
    validates :image
    validates :name,   length: { maximum: 30 } 
    validates :text,   length: { maximum: 100 }    
    validates :team_id
  end

  def self.search(search)
    if search != ""
      Tweet.where(['text LIKE(?) OR name LIKE(?)', "%#{search}%", "%#{search}%"])
    else
      Tweet.order("created_at DESC")
    end
  end
  
end

app/models/tweet_comment.rb
class TweetComment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  validates :text, presence: true, length: { maximum: 30 }
end

app/models/user.rb
class User < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  has_many :tweets
  has_many :chat_room_users
  has_many :chat_messages
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  has_many :sns_credentials
  belongs_to_active_hash :team
  mount_uploader :img_name, ImgNameUploader
  
  enum sex:{男: 0, 女: 1}
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  with_options presence: true do
    validates :nickname, length: { maximum: 30 }
    validates :birth_day
    validates :self_introduction, length: { maximum: 300}
    validates :sex
    validates :img_name
    validates :team_id
  end

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
      email: auth.info.email
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
  end

end
        

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  def create
    current_user_chat_rooms = ChatRoomUser.where(user_id: current_user.id).map(&:chat_room)
    chat_room = ChatRoomUser.where(chat_room: current_user_chat_rooms, user_id: params[:user_id]).map(&:chat_room).first
    if chat_room.blank?
      chat_room = ChatRoom.create
      ChatRoomUser.create(chat_room: chat_room, user_id: current_user.id)
      ChatRoomUser.create(chat_room: chat_room, user_id: params[:user_id])
    end
    redirect_to controller: :chat_message,action: :show, id: chat_room.id
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def chat
    @tweets = Tweet.all
    @teams = Team.all
  end

  def other
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, only:[:new, :create]

  def show
    @team = Team.find(params[:id])
    @tweets = Tweet.where(team_id: @team.id)
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.valid?
      @tweet.save
      redirect_to tweet_path(@tweet.team_id)
    else 
      render :new
    end
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    @tweet.update(tweet_params)
    if @tweet.valid?
      @tweet.save
      redirect_to tweet_path(@tweet.team_id)
    else
      render :discussion
    end
  end


  def destroy 
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to chat_home_index_path
  end
  
  def discussion
    @tweet = Tweet.find(params[:id])
    @tweet_comment = TweetComment.new
    @tweet_comments = TweetComment.where(tweet_id: @tweet.id)
  end

  def search
    @tweets = Tweet.search(params[:keyword])
  end

  private

  def tweet_params
    params.require(:tweet).permit(:name, :image, :text, :team_id).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.where.not(id:current_user.id)
  end

  def show
    @user = User.find(params[:id])
  end

  def follow
    @users =User.where(team_id: current_user.team_id).where.not(id: current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/chat_message_helper.rb
module ChatMessageHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/matching_helper.rb
module MatchingHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tweets/discussion.html.erb
<div class="discussion">
<%= render 'shared/header'%>
  <div class="container">
    <div class="discussion_tweet">
      <%= render partial: "shared/tweet", locals:{tweet: @tweet} %>
    </div>
    <div class="discussion_user">
      <% if user_signed_in? %>
        <% if current_user.id == @tweet.user_id %>
          <div class="discussion_user_edit userAction_common">
            <%= link_to(content_tag(:i, "", class: 'fas fa-cog fa-2x'), edit_tweet_path(@tweet.id)) %>
          </div>
          <div class="discussion_user_destroy userAction_common">
            <%= link_to(content_tag(:i, "", class: 'fa fa-trash fa-2x'),tweet_path(@tweet.id), method: :delete) %>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class="discussion_comment">
      <% if current_user %>
        <%= form_with(model: [@tweet, @tweet_comment], local: true) do |f| %>
          <%= f.text_area :text, placeholder: "コメントしよう！", rows:"2", class:"form-control" %>
          <%= f.submit "コメント", class:"discussion_comment_btn" %>
        <% end %>
      <% end %>
      <% if @tweet_comments %>
        <% @tweet_comments.each do |tweet_comment| %>
          <div class="discussion_comment_each">
            <strong><%= link_to tweet_comment.user.nickname, user_path(tweet_comment.user.id) %>
            <%= tweet_comment.text %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/tweets/edit.html.erb
<%= render 'shared/header'%>
<div class="main">
 <div class="container">
   <%= form_with(model: @tweet, local: true) do |form| %>
     <%= render partial: "shared/form", locals: { f: form } %>
   <% end %>
 </div>
</div>
<%= render 'shared/footer'%>

app/views/tweets/new.html.erb
<div class="tweet_new">
<%= render 'shared/header'%>  
  <header class="header">
    <div>新規投稿</div>
  </header>
 <div class="container">
   <%= form_with(model: @tweet, local: true) do |f| %>
     <%= render 'shared/error_messages', model: f.object %>
     <%= render partial: "shared/form", locals: { f: f } %>
   <% end %>
 </div>
</div>

app/views/tweets/search.html.erb
<div class="search">
<%= render 'shared/header'%>    
  <div class="container">
    <div class="row search_head">
      <div class="search_head_post">
        <%= link_to new_tweet_path, class:"search_head_post_btn" do %>
          <div class="search_head_post_btn_icon"><i class="fa fa-edit fa-2x"></i></div>
        <% end %>
      </div>
      <div class="search_head_search">
        <%= form_with(url: search_tweets_path, local: true, method: :get, class: "form-inline") do |f| %>
          <%= f.text_field :keyword, placeholder: '投稿を検索', class: "form-control" %>
          <%= f.submit "検索", class:"btn btn-outline-warning", style:"margin-left: 70px;" %>
        <% end %>
    </div>
    <div class="row search_tweets">
      <% @tweets.each do |tweet| %>
        <div class="search_tweets_each">
          <%= render partial: "shared/tweet", locals: { tweet: tweet} %>
        </div>
      <% end %>
    </div>
</div>

app/views/tweets/show.html.erb
<div class="tweet_show">
  <%= render 'shared/header'%>                 
    <div class="container">
      <div class="row tweet_show_team">
        <%= image_tag "#{@team.image}", class:"img-fluid tweet_show_team_logo", size:"150x150" %>
      </div>
      <div class="row tweet_show_article">
        <% @tweets.each do |tweet| %>
          <div class="tweet_show_article_each">
            <%= render partial: 'shared/tweet',locals:{tweet:tweet} %>
          </div>
        <% end %>
      </div>
    </div>
</div>