config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{ 
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root  'home#index'

  resources :home, only:[:index] do
    collection do
      get 'chat', 'other', 'seek'
    end
  end
  resources :tweets do
    member do
      get 'discussion'
    end
    collection do
      get 'search'
    end
    resources :tweet_comments, only: [:create]
  end

  resources :users,  only:[:index, :show] do
    collection do
      get 'follow'
    end
  end
  resources :reactions, only:[:create]
  resources :matching, only:[:index]
  resources :chat, only:[:create] 
  resources :chat_message, only:[:show, :create]
  resources :notifications, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_message.rb
class ChatMessage < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user

  validates :message, presence: true, length: { maximum: 500 }

  # after_create_commit { MessageBroadcastJob.perform_later self }

end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :chat_room_users
  has_many :chat_messages
end

app/models/chat_room_user.rb
class ChatRoomUser < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user
end

app/models/notification.rb
class Notification < ApplicationRecord

  default_scope -> { order(created_at: :desc) }
  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :to_user, class_name:"User"
  belongs_to :from_user, class_name:"User"

  enum status:{ like:0, dislike:1 }

  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = Notification.new(
        visitor_id: from_user_id,
        visited_id: to_user_id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  validates :to_user_id, presence: true
  validates :from_user_id, presence: true
  validates :status, presence: true
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belogns_to :user
end

app/models/team.rb
class Team < ActiveHash::Base
  self.data = [
    { id: 1, name: '秋田ノーザンハピネッツ', image: 'image/about01_02.png' },
    { id: 2, name: '横浜ビー・コルセアーズ', image: 'image/fl_club_primary.png' },
    { id: 3, name: '新潟アルビレックスBB',image: 'image/img_flag.gif' },
    { id: 4, name: '富山グラウジーズ',image: 'image/富山.png' },
    { id: 5, name: 'レバンガ北海道',image: 'image/square_levanga_logo.png' },
    { id: 6, name: '宇都宮ブレックス',image: 'image/ph00162920.png' },
    { id: 7, name: '千葉ジェッツ',image: 'image/chibajets_logo_2018-01.png' },
    { id: 8, name: 'アルバルク東京',image: 'image/alvark.png' },
    { id: 9, name: 'サンロッカーズ渋谷',image: 'image/sr.png' },
    { id: 10, name: '川崎ブレイブサンダース',image: 'image/201807022050_2-600x0.png' },
    { id: 11, name: '三遠ネオフェニックス',image: 'image/_____________.png' },
    { id: 12, name: '滋賀レイクスターズ',image: 'image/logo.png' },
    { id: 13, name: '京都ハンナリーズ',image: 'image/京都.jpg' },
    { id: 14, name: '大阪エヴェッサ',image: 'image/8FEcLku_.png' },
    { id: 15, name: '琉球ゴールデンキングス',image: 'image/rg.png' },
    { id: 16, name: '信州ブレイブウォリアーズ',image: 'image/FPfXFwON_400x400.png' },
    { id: 17, name: '島根スサノオマジック',image: 'image/島根.jpeg' },
    { id: 18, name: '広島ドラゴンフライズ',image: 'image/広島.png' },
    { id: 19, name: 'シーホース三河',image: 'image/三河.png' },
    { id: 20, name: '名古屋ダイヤモンドドルフィンズ',image: 'image/team-logo01.png' },
    { id: 21, name: 'その他', image: 'image/その他.png' }
  ]
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :team
  belongs_to :user
  has_many :tweet_comments, dependent: :destroy
  mount_uploader :image, ImageUploader

  with_options presence: true do
    validates :image
    validates :name,   length: { maximum: 30 } 
    validates :text,   length: { maximum: 100 }    
    validates :team_id
  end

  def self.search(search)
    if search != ""
      Tweet.where(['text LIKE(?) OR name LIKE(?)', "%#{search}%", "%#{search}%"])
    else
      Tweet.order("created_at DESC")
    end
  end
  
end

app/models/tweet_comment.rb
class TweetComment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  validates :text, presence: true, length: { maximum: 30 }
end

app/models/user.rb
class User < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  has_many :tweets
  has_many :chat_room_users
  has_many :chat_messages
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  has_many :sns_credentials
  belongs_to_active_hash :team
  mount_uploader :img_name, ImgNameUploader
  
  enum sex:{男: 0, 女: 1}
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  with_options presence: true do
    validates :nickname, length: { maximum: 30 }
    validates :birth_day
    validates :self_introduction, length: { maximum: 300}
    validates :sex
    validates :img_name
    validates :team_id
  end

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
      email: auth.info.email
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
  end

end
        

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  def create
    current_user_chat_rooms = ChatRoomUser.where(user_id: current_user.id).map(&:chat_room)
    chat_room = ChatRoomUser.where(chat_room: current_user_chat_rooms, user_id: params[:user_id]).map(&:chat_room).first
    if chat_room.blank?
      chat_room = ChatRoom.create
      ChatRoomUser.create(chat_room: chat_room, user_id: current_user.id)
      ChatRoomUser.create(chat_room: chat_room, user_id: params[:user_id])
    end
    redirect_to controller: :chat_message,action: :show, id: chat_room.id
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def chat
    @tweets = Tweet.all
    @teams = Team.all
  end

  def other
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.where.not(id:current_user.id)
  end

  def show
    @user = User.find(params[:id])
  end

  def follow
    @users =User.where(team_id: current_user.team_id).where.not(id: current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/chat_message_helper.rb
module ChatMessageHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/matching_helper.rb
module MatchingHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chat/show.html.erb
<div class="chatPage">
  <header class="header">
  <%= link_to "", matching_index_path, class: "linkToMatching" %>
    <div class="chatPartner">
      <div class="chatPartner_img"><%= image_tag "#{@chat_room_user.img_name}" %></div>
      <div class="chatPartner_name"><%= @chat_room_user.nickname %></div>
    </div>
  </header>
  <div class="container">
<<<<<<< Updated upstream
    <div class="messagesArea messages">
=======
    <div class="messagesArea messages" id="messages">
>>>>>>> Stashed changes
      <%= render @chat_messages %>
    </div>
  </div>
  <form class="messageInputForm">
    <div class='container'>
      <input type="text" data-behavior="room_speaker" class="messageInputForm_input" placeholder="メッセージを入力...">
    </div>
  </form>
<<<<<<< Updated upstream
</div>
=======
</div>
>>>>>>> Stashed changes

app/views/home/chat.html.erb
<div class="conversation">
<%= render 'shared/header'%>    
  <div class="container">
    <div class="row conversation_search">
      <h5 class="col conversation_search_text">チーム毎のニュースを確認できます</h5>
      <%= form_with(url: search_tweets_path, local: true, method: :get, class: "form-inline conversation_search_search") do |f| %>
        <%= f.text_field :keyword, placeholder: 'ニュースを検索', class: "form-control" %>
        <%= f.submit "検索", class:"btn btn-outline-warning" %>
      <% end %>
    </div>
    
    <div class="row conversation_teams">
      <% @teams.each do |team| %>
        <div class="col-xs-4 conversation_teams_each"> 
          <%= link_to tweet_path(team.id) do %>
          <%= image_tag "#{team.image}", class:"img-fluid", size:"159x159" %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
<%= render 'shared/footer'%>
</div>

app/views/home/index.html.erb
<%= render 'shared/header' %>
<div class="summary">
  <div class="container">
    <div class="col summary_timer ">
        <h4>東京五輪バスケ開催まで</h4>
        <p class="h4"><span id="day" class="h2"></span>日<span id="hour" class="h2"></span>時間<span id="min" class="h2"></span>分<span id="sec" class="h2"></span>秒</p>
    </div>
    <div class="row summary_up">
      <div class="col summary_up_title">
        <h4>MatchAppへようこそ</p>
        <h4><i class="fas fa-user-friends" style="color: darkoragen;"></i>仲間を集めよう</p>
      </div>
      <div class="col summary_up_search">
        <%= link_to seek_home_index_path, class:"summary_up_btn" do %>
          <div class="summary_up_btn_icon">はじめる</div>
        <% end %>
      </div>
    </div>
    <div class="row summary_down">
      <div class="col-xs-4">
        <%= link_to chat_home_index_path, class:"summary_down_btn" do %>
          <div class="summary_down_btn_icon"><i class="fas fa-basketball-ball"></i></div>
        <% end %>
      </div>
      <div class="col-xs-4">  
        <%= link_to other_home_index_path, class:"summary_down_btn" do %>
          <div class="summary_down_btn_icon"><i class="fa fa-gamepad"></i></div>
        <% end %>
      </div>
      <div class="col-xs-4">
      <a href="https://lin.ee/pHke6nm" class="summary_down_btn_line"></a>
      </div>
    </div>
  </div>
<%= render 'shared/footer' %>

<script>
  'use strict';

  function countdown(due) {
    const now = new Date();

    const rest = due.getTime() - now.getTime();
    const sec = Math.floor(rest / 1000) % 60;
    const min = Math.floor(rest / 1000 / 60) % 60;
    const hours = Math.floor(rest / 1000 / 60 / 60) % 24;
    const days = Math.floor(rest / 1000 / 60 / 60 / 24);
    const count = [days, hours, min, sec];

    return count;
}


function recalc(){
  const counter = countdown(goal);
  document.getElementById('day').textContent = counter[0];
  document.getElementById('hour').textContent = counter[1];
  document.getElementById('min').textContent = String(counter[2]).padStart(2, '0');
  document.getElementById('sec').textContent = String(counter[3]).padStart(2, '0');
  refresh();
}

function refresh(){
  setTimeout(recalc, 1000);
}

let goal = new Date(2021, 7, 25);
recalc();

</script>

app/views/home/other.html.erb
<%= render 'shared/header' %>
<div class="other">
  <div class="container"> 
    <div class="row other_head">🏀バスケットボール検定🏀</div>
    <div class="row other_q" id="text_q"></div>
    <div class="row other_s" id="text_s" ></div>
    <div class="row other_foot">前の問題の答え</div>
    <div class="row other_a" id="text_a"></div>
  </div>
</div>
<%= render 'shared/footer' %>

<script type="text/javascript">

qa = new Array();
    qa[0] = ["バスケットの神様と呼ばれるNBA史上最高の選手は？","レブロン・ジェームス","コービー・ブライアント","ケビン・ガーネット","マイケル・ジョーダン",4];
    qa[1] = ["日本人初となるNBAドラフト1巡目指名された八村塁選手ですが、どのチームから指名されたでしょうか？","ワシントン・ウィザーズ","ロサンゼルス・レイカーズ","クリーブラント・キャバリアーズ","ヒューストン・ロケッツ",1];
    qa[2] = ["Bリーグ初年度の優勝チームは？","宇都宮ブレックス","アルバルク東京","川崎ブレイブサンダース","名古屋ダイヤモンドドルフィンズ",1];
    qa[3] = ["Bリーグ初年度のMVPは？","田中大貴","富樫勇樹","ニック・ファジーカス","八村塁", 3];
    qa[4] = ["この中でNBAのチームに在籍していたことがない選手は？","ライアン・ロシター","ジョシュ・ハレルソン","ニック・ファジーカス","田臥勇太",1];
    qa[5] = ["比江島慎の身長は？","188cm","190cm","192cm","195cm",2];
    qa[6] = ["B1リーグのチーム数は？","15","20","25","30",2];
    qa[7] = ["B2リーグのチーム数は？","12","14","16","20",3];
    qa[8] = ["名古屋ダイヤモンドドルフィンズのマスコットの名前は？","ドルちゃん","ブラックマンバ","エドワード","ディー・ディー",4];
    qa[9] = ["斎藤拓実の出身校として誤っているものは？","桐光学園高校","明治大学","白鳥中学","福岡第一高校",4];

    q_sel = 4;
    q_max = 10;
    setReady();

    function setReady(){
      count = 0;
      answers = new Array();
      randoms = new Array();
      quiz();
    };

    function getRandom(){
      let random_1 = Math.floor(Math.random()*10)
      if(!(randoms.includes(random_1))){
        randoms.push(random_1);
        return random_1;
      }else{
        let random_2 = random_1;
        while(randoms.includes(random_2)){ 
          let random_2 = Math.floor(Math.random()*10)
          if(!(randoms.includes(random_2))){
            randoms.push(random_2);
            console.log(randoms);
            return random_2;
          }
        }
      }
    }

    function quiz(){
      let s;
      let n;
      random = getRandom();
      document.getElementById("text_q").innerHTML = "第"+(count+1)+"問🏀"+qa[random][0];
      s = "";
      for(n=1; n<=q_sel; n++){
        if(qa[random][n] != ""){
          s += "<a href='javascript:answer(" + n + ")' class='other_choice'>" + n + "：" + qa[random][n] + "</a>";
        }
      }
      document.getElementById("text_s").innerHTML = s;
    };

    function answer(num){
      let s;
      s = (count+ 1)+"問目：";
      if(num === qa[random][q_sel+1]){
        answers[count] = "○";
      }else{
        answers[count] = "✗";
      }
      s += answers[count]+qa[random][num];
      document.getElementById("text_a").innerHTML = s;

      count++;
      if(count<q_max){
        quiz();
      }else{
        s = "<table border='2'><caption style='color: darkorange; margin-top: 60px;'>8問以上正解で自慢しよう！</caption>";
        s += "<tr><th>問題</th>";
        for(n=0; n<qa.length; n++){
          s += "<th>"+(n+1)+"</th>";
        }
        s += "</tr>";
        s += "<tr><th>成績</th>";
        for(n=0; n<qa.length; n++){
          s += "<td>" + answers[n] + "</td>";
        }
        s += "</tr>";
        s += "</table>";
        document.getElementById("text_q").innerHTML = s;

        s = "<a href='javascript:history.back()' style='color:white; margin-top:30px; text-decoration-color: darkorange;'>トップページ</a>";
        s += "<a href='javascript:setReady()' style='color:white; margin-top:30px; text-decoration-color: darkorange;'>最初から</a>";
        document.getElementById("text_s").innerHTML = s;
      }
    };

</script>

app/views/home/seek.html.erb
<%= render 'shared/header' %>

<div class="loginPage">
  <div class="container">
    <div class="loginPage_contents">
      <h1 class="h3 loginPage_contents_title">バスケでつながろう</h1>
      <%= link_to "さあ、はじめよう！", users_path, class:"btn loginPage_contents_btn"%>
      <%= link_to "メールアドレスでログインする", new_user_session_path, class: "btn loginPage_contents_btn" %>
    </div>
  </div>
</div>